/* Embed Lua source files as uncompressed C byte arrays.
 *
 * Same output schema as scripts/embed_lua.c (struct psi_embedded_lua
 * with name / src / len / raw_len) but skips zlib compression so
 * the AmigaOS m68k cross-build doesn't need libz. `len == raw_len`
 * marks "raw" entries to the runtime; the AmigaOS searcher just
 * does luaL_loadbuffer(src, len) without inflating.
 *
 * Usage: embed_lua_raw [--table=NAME] <file1> [<file2> ...] > out.c
 * Defaults to --table=psi_embedded_lua_table; module names derived
 * from path (lua/boot.lua -> "boot"; lua/psi/prelude.lua ->
 * "psi.prelude"). */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void derive_modname(const char *path, char *out, size_t out_size)
{
    const char *start = path;
    size_t prefix_len = 4; /* strip "lua/" */
    size_t i, j;
    if (strncmp(start, "lua/", 4) == 0) start += prefix_len;

    /* Drop ".lua" suffix. */
    {
        size_t plen = strlen(start);
        if (plen > 4 && strcmp(start + plen - 4, ".lua") == 0) {
            plen -= 4;
        }
        if (plen >= out_size) plen = out_size - 1;
        for (i = 0, j = 0; i < plen; i++) {
            char c = start[i];
            if (c == '/') c = '.';
            out[j++] = c;
        }
        out[j] = '\0';
    }
}

static int emit_one(FILE *f, const char *path, size_t idx)
{
    FILE *in;
    long n;
    unsigned char buf[4096];
    size_t got;
    size_t total = 0;
    size_t col = 0;

    in = fopen(path, "rb");
    if (in == NULL) {
        fprintf(stderr, "embed_lua_raw: cannot open %s\n", path);
        return -1;
    }

    fprintf(f, "static const unsigned char emb_%zu_src[] = {\n  ", idx);
    while ((got = fread(buf, 1, sizeof(buf), in)) > 0) {
        size_t i;
        for (i = 0; i < got; i++) {
            fprintf(f, "0x%02x,", buf[i]);
            total++;
            col++;
            if (col == 16) { fprintf(f, "\n  "); col = 0; }
        }
    }
    fprintf(f, "\n};\n");
    fclose(in);
    /* Returning total — caller writes the table entry. */
    n = (long)total;
    return (int)(n & 0x7FFFFFFF);
}

int main(int argc, char **argv)
{
    const char *table_name = "psi_embedded_lua_table";
    int raw_keys = 0;
    int i, first;
    int *sizes;
    int rc = 0;

    /* Parse flags. */
    first = 1;
    while (first < argc && strncmp(argv[first], "--", 2) == 0) {
        if (strncmp(argv[first], "--table=", 8) == 0) {
            table_name = argv[first] + 8;
        } else if (strcmp(argv[first], "--raw-keys") == 0) {
            raw_keys = 1;
        } else if (strcmp(argv[first], "--") == 0) {
            first++;
            break;
        } else {
            fprintf(stderr, "embed_lua_raw: unknown flag %s\n", argv[first]);
            return 2;
        }
        first++;
    }

    if (first >= argc) {
        fprintf(stderr, "embed_lua_raw: no input files\n");
        return 2;
    }

    sizes = (int *)calloc((size_t)argc, sizeof(int));
    if (sizes == NULL) return 2;

    fprintf(stdout, "/* Auto-generated by amigaos/scripts/embed_lua_raw.c */\n");
    fprintf(stdout, "#include <stddef.h>\n");
    fprintf(stdout, "#include \"psi/embedded_lua.h\"\n\n");

    for (i = first; i < argc; i++) {
        int len = emit_one(stdout, argv[i], (size_t)(i - first));
        if (len < 0) { rc = 1; goto done; }
        sizes[i] = len;
    }

    fprintf(stdout, "\nconst struct psi_embedded_lua %s[] = {\n",
            table_name);
    for (i = first; i < argc; i++) {
        char modname[256];
        if (raw_keys) {
            strncpy(modname, argv[i], sizeof(modname) - 1);
            modname[sizeof(modname) - 1] = '\0';
        } else {
            derive_modname(argv[i], modname, sizeof(modname));
        }
        fprintf(stdout,
                "  {\"%s\", emb_%zu_src, %dU, %dU},\n",
                modname, (size_t)(i - first), sizes[i], sizes[i]);
    }
    fprintf(stdout, "  {NULL, NULL, 0U, 0U}\n};\n");

done:
    free(sizes);
    return rc;
}
