/* Empty embedded-Lua tables. The full version is generated by
 * scripts/embed_lua.c at build time and bakes every lua/*.lua into
 * the binary. For the 9front MVP we rely on the lua/ dir being on
 * disk, so both tables are just the sentinel entry. Matches the
 * symbols declared in include/psi/embedded_lua.h. */

#include <stddef.h>
#include "psi/embedded_lua.h"

const struct psi_embedded_lua psi_embedded_lua_table[] = {
    { NULL, NULL, 0, 0 }
};

const struct psi_embedded_lua psi_embedded_docs_table[] = {
    { NULL, NULL, 0, 0 }
};
