/* Generate a C file that embeds Lua sources as byte arrays plus a
 * lookup table used by psi_vm's embedded `package.searchers` entry.
 *
 * Usage:   embed_lua <file1.lua> [<file2.lua> ...] > embedded_lua.c
 *
 * Module names are derived from the input paths:
 *   lua/boot.lua          -> "boot"
 *   lua/psi/prelude.lua   -> "psi.prelude"
 *   lua/psi/tool_shell.lua-> "psi.tool_shell"
 *
 * The binary only runs at build time on the host; it has no psi
 * dependencies and uses only <stdio.h>/<string.h>/<stdlib.h>. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void derive_modname(const char *path, char *out, size_t out_size) {
    const char *start = path;
    size_t prefix_len = 4;
    if (strncmp(start, "lua/", prefix_len) == 0) {
        start += prefix_len;
    }
    size_t len = strlen(start);
    if (len >= 4 && strcmp(start + len - 4, ".lua") == 0) {
        len -= 4;
    }
    if (len >= out_size) len = out_size - 1;
    size_t i;
    for (i = 0; i < len; i++) {
        out[i] = (start[i] == '/') ? '.' : start[i];
    }
    out[i] = '\0';
}

static void sanitize_symbol(const char *in, char *out, size_t out_size) {
    size_t i;
    for (i = 0; i + 1 < out_size && in[i]; i++) {
        char c = in[i];
        int ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
              || (c >= '0' && c <= '9');
        out[i] = ok ? c : '_';
    }
    out[i] = '\0';
}

static int emit_bytes(const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return -1; }
    int c, n = 0;
    while ((c = fgetc(f)) != EOF) {
        if (n > 0) {
            fputc(',', stdout);
            if (n % 16 == 0) {
                fputs("\n    ", stdout);
            }
        } else {
            fputs("\n    ", stdout);
        }
        printf("0x%02x", (unsigned char)c);
        n++;
    }
    fclose(f);
    return n;
}

int main(int argc, char **argv) {
    int i;
    if (argc < 2) {
        fprintf(stderr, "usage: %s <file1.lua> [<file2.lua> ...]\n", argv[0]);
        return 1;
    }

    printf("/* Auto-generated by scripts/embed_lua.c; do not edit. */\n");
    printf("#include <stddef.h>\n");
    printf("#include \"psi/embedded_lua.h\"\n\n");

    for (i = 1; i < argc; i++) {
        char modname[256];
        char sym[256];
        derive_modname(argv[i], modname, sizeof(modname));
        sanitize_symbol(modname, sym, sizeof(sym));
        printf("static const unsigned char lua_%s_src[] = {", sym);
        if (emit_bytes(argv[i]) < 0) return 1;
        printf("\n};\n\n");
    }

    printf("const struct psi_embedded_lua psi_embedded_lua_table[] = {\n");
    for (i = 1; i < argc; i++) {
        char modname[256];
        char sym[256];
        derive_modname(argv[i], modname, sizeof(modname));
        sanitize_symbol(modname, sym, sizeof(sym));
        printf("    { \"%s\", lua_%s_src, sizeof(lua_%s_src) },\n",
               modname, sym, sym);
    }
    printf("    { NULL, NULL, 0u }\n");
    printf("};\n");
    return 0;
}
