/* Generate a C file that embeds arbitrary files as DEFLATE-compressed
 * byte arrays plus a sentinel-terminated lookup table.
 *
 * Usage:
 *   embed_lua [--table=NAME] [--raw-keys] <file1> [<file2> ...] > out.c
 *
 * Default behavior (Lua modules):
 *   --table=psi_embedded_lua_table
 *   module names derived from path:
 *     lua/boot.lua          -> "boot"
 *     lua/psi/prelude.lua   -> "psi.prelude"
 *
 * With --raw-keys the input path is used verbatim as the lookup key
 * (useful for doc files: "README.md" stays "README.md"). The
 * --table flag picks which symbol the generated table is exposed as
 * so multiple invocations can coexist in the same binary.
 *
 * Each file is compressed with zlib at level 9 before being emitted;
 * the runtime inflates on first access. Decreases binary size
 * significantly (Lua + docs ~170 KB -> ~55 KB). Tool runs at build
 * time on the host and requires -lz. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <zlib.h>

static void derive_modname(const char *path, char *out, size_t out_size) {
    const char *start = path;
    size_t prefix_len = 4;
    if (strncmp(start, "lua/", prefix_len) == 0) {
        start += prefix_len;
    }
    size_t len = strlen(start);
    if (len >= 4 && strcmp(start + len - 4, ".lua") == 0) {
        len -= 4;
    }
    if (len >= out_size) len = out_size - 1;
    size_t i;
    for (i = 0; i < len; i++) {
        out[i] = (start[i] == '/') ? '.' : start[i];
    }
    out[i] = '\0';
}

static void sanitize_symbol(const char *in, char *out, size_t out_size) {
    size_t i;
    for (i = 0; i + 1 < out_size && in[i]; i++) {
        char c = in[i];
        int ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
              || (c >= '0' && c <= '9');
        out[i] = ok ? c : '_';
    }
    out[i] = '\0';
}

/* Read the whole file into memory. Returns 0/size on success, -1 on failure. */
static unsigned char *slurp(const char *path, size_t *len_out) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return NULL; }
    long size = ftell(f);
    if (size < 0) { fclose(f); return NULL; }
    rewind(f);
    unsigned char *buf = (unsigned char *)malloc((size_t)size + 1u);
    if (!buf) { fclose(f); return NULL; }
    size_t got = fread(buf, 1u, (size_t)size, f);
    fclose(f);
    if (got != (size_t)size) { free(buf); return NULL; }
    buf[size] = 0;
    *len_out = (size_t)size;
    return buf;
}

/* Deflate `in` to a newly-malloc'd buffer. Returns length or -1 on error. */
static long deflate_bytes(const unsigned char *in, size_t in_len,
                          unsigned char **out_buf) {
    /* Upper bound per zlib manual: compressBound(n). For our input
     * sizes a comfortable 1.2x + 128 suffices too. */
    uLongf bound = compressBound((uLong)in_len);
    unsigned char *out = (unsigned char *)malloc(bound);
    if (!out) return -1;
    int rc = compress2(out, &bound, in, (uLong)in_len, 9);
    if (rc != Z_OK) { free(out); fprintf(stderr, "deflate: %d\n", rc); return -1; }
    *out_buf = out;
    return (long)bound;
}

static void emit_bytes(const unsigned char *bytes, size_t n) {
    size_t i;
    for (i = 0; i < n; i++) {
        if (i > 0) {
            fputc(',', stdout);
            if (i % 16 == 0) fputs("\n    ", stdout);
        } else {
            fputs("\n    ", stdout);
        }
        printf("0x%02x", bytes[i]);
    }
}

int main(int argc, char **argv) {
    const char *table_name = "psi_embedded_lua_table";
    int raw_keys = 0;
    int i;
    int first_file;

    /* Parse leading options. */
    first_file = 1;
    while (first_file < argc) {
        const char *a = argv[first_file];
        if (strncmp(a, "--table=", 8) == 0) {
            table_name = a + 8;
            first_file++;
        } else if (strcmp(a, "--raw-keys") == 0) {
            raw_keys = 1;
            first_file++;
        } else if (a[0] == '-' && a[1] == '-') {
            fprintf(stderr, "unknown option: %s\n", a);
            return 1;
        } else {
            break;
        }
    }
    if (first_file >= argc) {
        fprintf(stderr,
            "usage: %s [--table=NAME] [--raw-keys] <file1> [<file2> ...]\n",
            argv[0]);
        return 1;
    }

    printf("/* Auto-generated by scripts/embed_lua.c; do not edit. */\n");
    printf("#include <stddef.h>\n");
    printf("#include \"psi/embedded_lua.h\"\n\n");

    /* Track sizes so we can emit the table after the byte arrays. */
    size_t count = (size_t)(argc - first_file);
    size_t *raw_lens = (size_t *)calloc(count, sizeof(size_t));
    size_t *zlen = (size_t *)calloc(count, sizeof(size_t));
    char **syms = (char **)calloc(count, sizeof(char *));
    char **keys = (char **)calloc(count, sizeof(char *));
    if (!raw_lens || !zlen || !syms || !keys) {
        fprintf(stderr, "embed_lua: out of memory\n");
        return 1;
    }

    for (i = first_file; i < argc; i++) {
        size_t k = (size_t)(i - first_file);
        char buf[512];
        char symbuf[256];
        if (raw_keys) {
            snprintf(buf, sizeof(buf), "%s", argv[i]);
        } else {
            derive_modname(argv[i], buf, sizeof(buf));
        }
        sanitize_symbol(buf, symbuf, sizeof(symbuf));
        keys[k] = strdup(buf);
        syms[k] = strdup(symbuf);

        size_t raw_len = 0;
        unsigned char *raw = slurp(argv[i], &raw_len);
        if (!raw) return 1;
        unsigned char *compressed = NULL;
        long clen = deflate_bytes(raw, raw_len, &compressed);
        free(raw);
        if (clen < 0) return 1;

        raw_lens[k] = raw_len;
        zlen[k] = (size_t)clen;

        printf("static const unsigned char emb_%s_src[] = {", syms[k]);
        emit_bytes(compressed, (size_t)clen);
        printf("\n};\n\n");
        free(compressed);
    }

    printf("const struct psi_embedded_lua %s[] = {\n", table_name);
    for (i = 0; i < (int)count; i++) {
        printf("    { \"%s\", emb_%s_src, %zuu, %zuu },\n",
               keys[i], syms[i], zlen[i], raw_lens[i]);
    }
    printf("    { NULL, NULL, 0u, 0u }\n");
    printf("};\n");
    return 0;
}
