/* Generate a C file that embeds arbitrary files as byte arrays plus a
 * sentinel-terminated lookup table.
 *
 * Usage:
 *   embed_lua [--table=NAME] [--raw-keys] <file1> [<file2> ...] > out.c
 *
 * Default behavior (Lua modules):
 *   --table=psi_embedded_lua_table
 *   module names derived from path:
 *     lua/boot.lua          -> "boot"
 *     lua/psi/prelude.lua   -> "psi.prelude"
 *
 * With --raw-keys the input path is used verbatim as the lookup key
 * (useful for doc files: "README.md" stays "README.md"). The
 * --table flag picks which symbol the generated table is exposed as
 * so multiple invocations can coexist in the same binary.
 *
 * The binary only runs at build time on the host; it has no psi
 * dependencies and uses only <stdio.h>/<string.h>/<stdlib.h>. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void derive_modname(const char *path, char *out, size_t out_size) {
    const char *start = path;
    size_t prefix_len = 4;
    if (strncmp(start, "lua/", prefix_len) == 0) {
        start += prefix_len;
    }
    size_t len = strlen(start);
    if (len >= 4 && strcmp(start + len - 4, ".lua") == 0) {
        len -= 4;
    }
    if (len >= out_size) len = out_size - 1;
    size_t i;
    for (i = 0; i < len; i++) {
        out[i] = (start[i] == '/') ? '.' : start[i];
    }
    out[i] = '\0';
}

static void sanitize_symbol(const char *in, char *out, size_t out_size) {
    size_t i;
    for (i = 0; i + 1 < out_size && in[i]; i++) {
        char c = in[i];
        int ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
              || (c >= '0' && c <= '9');
        out[i] = ok ? c : '_';
    }
    out[i] = '\0';
}

static int emit_bytes(const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return -1; }
    int c, n = 0;
    while ((c = fgetc(f)) != EOF) {
        if (n > 0) {
            fputc(',', stdout);
            if (n % 16 == 0) {
                fputs("\n    ", stdout);
            }
        } else {
            fputs("\n    ", stdout);
        }
        printf("0x%02x", (unsigned char)c);
        n++;
    }
    fclose(f);
    return n;
}

int main(int argc, char **argv) {
    const char *table_name = "psi_embedded_lua_table";
    int raw_keys = 0;
    int i;
    int first_file;

    /* Parse leading options. */
    first_file = 1;
    while (first_file < argc) {
        const char *a = argv[first_file];
        if (strncmp(a, "--table=", 8) == 0) {
            table_name = a + 8;
            first_file++;
        } else if (strcmp(a, "--raw-keys") == 0) {
            raw_keys = 1;
            first_file++;
        } else if (a[0] == '-' && a[1] == '-') {
            fprintf(stderr, "unknown option: %s\n", a);
            return 1;
        } else {
            break;
        }
    }
    if (first_file >= argc) {
        fprintf(stderr,
            "usage: %s [--table=NAME] [--raw-keys] <file1> [<file2> ...]\n",
            argv[0]);
        return 1;
    }

    printf("/* Auto-generated by scripts/embed_lua.c; do not edit. */\n");
    printf("#include <stddef.h>\n");
    printf("#include \"psi/embedded_lua.h\"\n\n");

    for (i = first_file; i < argc; i++) {
        char key[512];
        char sym[256];
        if (raw_keys) {
            /* Key is the path verbatim; symbol needs sanitization only. */
            snprintf(key, sizeof(key), "%s", argv[i]);
        } else {
            derive_modname(argv[i], key, sizeof(key));
        }
        sanitize_symbol(key, sym, sizeof(sym));
        printf("static const unsigned char emb_%s_src[] = {", sym);
        if (emit_bytes(argv[i]) < 0) return 1;
        printf("\n};\n\n");
    }

    printf("const struct psi_embedded_lua %s[] = {\n", table_name);
    for (i = first_file; i < argc; i++) {
        char key[512];
        char sym[256];
        if (raw_keys) {
            snprintf(key, sizeof(key), "%s", argv[i]);
        } else {
            derive_modname(argv[i], key, sizeof(key));
        }
        sanitize_symbol(key, sym, sizeof(sym));
        printf("    { \"%s\", emb_%s_src, sizeof(emb_%s_src) },\n",
               key, sym, sym);
    }
    printf("    { NULL, NULL, 0u }\n");
    printf("};\n");
    return 0;
}
