-- gen-docs.lua: emit psi.1 and rewrite the @generated:cli-options
-- region of docs/architecture.md from src/runtime/cli.c.
--
-- Most introspection happens at runtime via psi.doc + /describe +
-- /apropos (lua/psi/doc.lua). Only the surface that someone needs
-- *before* installing psi (CLI flags) and the man page (read by
-- people who have the binary but want quick reference outside the
-- agent) are pre-rendered into markdown / mdoc.
--
-- Run via:
--   ./build/psi --eval 'dofile("scripts/gen-docs.lua")'
--
-- Or `make docs` / `make check-docs` (the latter asserts no diff).

local slash = require("psi.slash_commands")
local api_registry = require("psi.api_registry")

local M = {}

-- ---------------------------------------------------------------- io --

local function read_file(path)
  local fh, err = io.open(path, "rb")
  if not fh then
    error("read: " .. tostring(err))
  end
  local body = fh:read("*a")
  fh:close()
  return body
end

local function write_file(path, body)
  local fh, err = io.open(path, "wb")
  if not fh then
    error("write: " .. tostring(err))
  end
  fh:write(body)
  fh:close()
end

local function escape_pat(s)
  return (s:gsub("([^%w])", "%%%1"))
end

local function replace_region(body, name, replacement)
  local marker_open = "<!%-%- @generated:" .. escape_pat(name) .. " %-%->"
  local marker_close = "<!%-%- @end %-%->"
  local pat = "(" .. marker_open .. "\n).-(" .. marker_close .. ")"
  local trimmed = replacement:gsub("\n+$", "")
  local replaced, n = body:gsub(pat, function(open, close)
    return open .. trimmed .. "\n" .. close
  end)
  if n == 0 then
    error(("region @generated:%s not found"):format(name))
  end
  return replaced
end

-- -------------------------------------------------------- generators --

-- ----------------------------------------------------------- C parsing --

local function parse_cli_options(source)
  local opts = {}
  for short, long, var, desc in
    source:gmatch('arg_str0%(([^,]+),%s*"([%w-]+)",%s*"([^"]+)",%s*"([^"]-)"%)')
  do
    opts[#opts + 1] = {
      kind = "str",
      short = short:match('"(.-)"'),
      long = long,
      var = var,
      desc = desc,
    }
  end
  for short, long, desc in
    source:gmatch('arg_lit0%(([^,]+),%s*"([%w-]+)",%s*"([^"]-)"%)')
  do
    opts[#opts + 1] = {
      kind = "lit",
      short = short:match('"(.-)"'),
      long = long,
      desc = desc,
    }
  end
  for short, long, var, desc in
    source:gmatch('arg_int0%(([^,]+),%s*"([%w-]+)",%s*"([^"]+)",%s*"([^"]-)"%)')
  do
    opts[#opts + 1] = {
      kind = "int",
      short = short:match('"(.-)"'),
      long = long,
      var = var,
      desc = desc,
    }
  end
  table.sort(opts, function(a, b)
    return a.long < b.long
  end)
  return opts
end

function M.cli_options_table()
  local source = read_file("src/runtime/cli.c")
  local opts = parse_cli_options(source)
  local lines = {
    "| Flag | Argument | Description |",
    "|---|---|---|",
  }
  for _, opt in ipairs(opts) do
    local flag
    if opt.short and opt.short ~= "" then
      flag = string.format("`-%s`, `--%s`", opt.short, opt.long)
    else
      flag = string.format("`--%s`", opt.long)
    end
    local arg = opt.var and ("`" .. opt.var .. "`") or "—"
    lines[#lines + 1] = string.format("| %s | %s | %s |", flag, arg, opt.desc)
  end
  return table.concat(lines, "\n")
end

-- ------------------------------------------------------- man page --

local function man_escape(s)
  return (s:gsub("\\", "\\\\"):gsub("%-", "\\-"))
end

function M.man_page()
  local out = {}
  local function emit(fmt, ...)
    out[#out + 1] = string.format(fmt, ...)
  end
  emit('.\\" Auto-generated by scripts/gen-docs.lua. Do not edit by hand.')
  emit(".TH PSI 1 \"\" \"psi\" \"User Commands\"")
  emit(".SH NAME")
  emit("psi \\- terminal coding agent")
  emit(".SH SYNOPSIS")
  emit(".B psi")
  emit("[\\fIoptions\\fR] [\\fImessage\\fR]")
  emit(".SH DESCRIPTION")
  emit("psi is a small terminal coding agent. The host runtime is C89;")
  emit("the agent loop, providers, and TUI are pure Lua. With no flags,")
  emit("psi opens the inline TUI over the same runtime that")
  emit("\\fB--print\\fR, \\fB--agent\\fR, and \\fB--repl\\fR drive.")
  emit(".SH OPTIONS")
  local cli = parse_cli_options(read_file("src/runtime/cli.c"))
  for _, opt in ipairs(cli) do
    local label
    if opt.short and opt.short ~= "" then
      label = string.format("\\fB-%s\\fR, \\fB\\-\\-%s\\fR", opt.short, opt.long)
    else
      label = string.format("\\fB\\-\\-%s\\fR", opt.long)
    end
    if opt.var then
      label = label .. " \\fI" .. opt.var .. "\\fR"
    end
    emit(".TP")
    emit(label)
    emit(man_escape(opt.desc))
  end
  emit(".SH SLASH COMMANDS")
  emit("Available inside the interactive shell and TUI:")
  emit(".PP")
  for _, cmd in ipairs(slash.builtin_commands()) do
    emit(".TP")
    local args = cmd.argument_hint and (" " .. cmd.argument_hint) or ""
    emit("\\fB/%s%s\\fR", cmd.name, args)
    emit(man_escape(cmd.description or ""))
    if cmd.aliases and #cmd.aliases > 0 then
      local aliases = {}
      for _, a in ipairs(cmd.aliases) do
        aliases[#aliases + 1] = "/" .. a
      end
      emit("Aliases: %s", table.concat(aliases, ", "))
    end
  end
  emit(".SH PROVIDERS")
  local providers = api_registry.all_providers()
  local pnames = {}
  for _, entry in ipairs(providers) do
    if type(entry) == "table" and type(entry.name) == "string" then
      pnames[#pnames + 1] = entry.name
    end
  end
  table.sort(pnames)
  for _, name in ipairs(pnames) do
    local spec = api_registry.provider(name) or {}
    emit(".TP")
    emit("\\fB%s\\fR", name)
    emit(
      "default model %s, override via %s",
      spec.default_model or "n/a",
      spec.model_env or "—"
    )
  end
  emit(".SH ENVIRONMENT")
  emit(".TP")
  emit("\\fBPSI_PROVIDER\\fR")
  emit("Override default provider: " .. table.concat(pnames, ", ") .. ".")
  emit(".TP")
  emit("\\fBPSI_EXTENSIONS_DIR\\fR")
  emit("Colon-separated list of extension directories scanned at boot.")
  emit(".TP")
  emit("\\fBANTHROPIC_API_KEY\\fR")
  emit("Required for the Anthropic provider.")
  emit(".SH FILES")
  emit(".TP")
  emit("\\fI~/.config/psi/settings.json\\fR")
  emit("User-level layered settings.")
  emit(".TP")
  emit("\\fI./.psi/settings.json\\fR")
  emit("Project-level settings (overrides user).")
  emit(".TP")
  emit("\\fI~/.config/psi/extensions/\\fR, \\fI./.psi/extensions/\\fR")
  emit("Lua extensions loaded at boot.")
  emit(".SH SEE ALSO")
  emit("Documentation under \\fIdocs/\\fR: architecture.md, extensions.md,")
  emit("portability.md, port-status.md, providers.md.")
  return table.concat(out, "\n") .. "\n"
end

-- ---------------------------------------------------------- driver --

local function update(path, regions)
  local body = read_file(path)
  for name, content in pairs(regions) do
    body = replace_region(body, name, content)
  end
  write_file(path, body)
  print("updated " .. path)
end

-- The set of regions kept in markdown is deliberately small: just
-- the things a reader needs *before* installing psi (CLI flags) plus
-- the man page (read by someone who has the binary but doesn't want
-- to launch it). Slash commands, tools, keybindings, providers, and
-- host primitives are all queryable at runtime via /describe and
-- /apropos — see lua/psi/doc.lua. Don't add a new generated region
-- for something the running program already knows about itself.
local function run()
  update("docs/architecture.md", {
    ["cli-options"] = M.cli_options_table(),
  })
  write_file("psi.1", M.man_page())
  print("wrote psi.1")
end

run()
return M
